### ISSUE TITLE
Import libsimpa to python

### ISSUE THREAD

**Issue by d-cooper** [Ifsttar/I-Simpa#107]
Hello,

I need to write a script for batch converting .recp to .csv. I know that there is a similar one in samples for .pbin, but have problems importing libsimpa from outside the I-SIMPA.

In the sample there is just:
`import libsimpa as ls`
but it doesnt work because it doesn't know where libsimpa is

when I try coping libsimpa to the same folder or using:

```
import sys
sys.path.append('../../libsimpa')
import libsimpa as ls
```

I get following error:

>   File "offline-convert.py", line 3, in <module>
>     import libsimpa as ls
>   File "D:\Wojtek\Programy\I-SIMPA\I-Simpa - proj\bin\UserScript\export_to_csv_tool\libsimpa.py", line 21, in <module>
>     _libsimpa = swig_import_helper()
>   File "D:\Wojtek\Programy\I-SIMPA\I-Simpa - proj\bin\UserScript\export_to_csv_tool\libsimpa.py", line 20, in swig_import_helper
>     return importlib.import_module('_libsimpa')
>   File "C:\Program Files\Python27\Lib\importlib\__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: DLL load failed:

Sorry, I am not an python expert... What am I doing wrong?

Thanks

**Comment by nicolas-f** [comment]
Hi,

I-Simpa is now based on python 2.7 64 bits. Copy-Paste libsimpa folder into:

 `C:\Python27\Lib\site-packages`

**Comment by nicolas-f** [comment]
I should have start with this. What is the version of I-Simpa ? Do you have compiled it yourself ?

**Comment by d-cooper** [comment]
I use my own build. Yesterday I merged Isimpa-master so it schould be up to date. It is build using MS Visual Studio 2015 CE, boost 1.62, python 2.7.13 x64. I've tried latest swig 3.0.12 as well as some older ones 3.0.10 and 3.0.8.

Moreover the libsimpa works perfectly well within I-SIMPA.

**Comment by nicolas-f** [comment]
I-Simpa is now compiled on the cloud for windows too.

Using this snapshot dev version copying libsimpa works on my pc:
https://ci.appveyor.com/project/nicolas-f/I-Simpa/build/artifacts

ps: You could also use AppVeyor to build your fork on the cloud too.

**Comment by d-cooper** [comment]
I am sorry for the trouble but I've downloaded the snapshot and copied the files but it still doesn't work.

```
C:\Users\wojci>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsimpa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python27\lib\site-packages\libsimpa\__init__.py", line 2, in <module>
    from libsimpa import *
  File "C:\Program Files\Python27\lib\site-packages\libsimpa\libsimpa.py", line 17, in <module>
    _libsimpa = swig_import_helper()
  File "C:\Program Files\Python27\lib\site-packages\libsimpa\libsimpa.py", line 16, in swig_import_helper
    return importlib.import_module('_libsimpa')
  File "C:\Program Files\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _libsimpa
>>>
```

**Comment by nicolas-f** [comment]
Maybe link with this issue:
https://github.com/swig/swig/issues/769

I have to understand what is going wrong here.

**Comment by d-cooper** [comment]
I've noticed it and tried to use swig 3.0.8 but with no result. In the evening I will try it on other pc. If I will find something out I will let you know.
Thanks for help!

**Comment by nicolas-f** [comment]
Please check with http://www.dependencywalker.com in order to find if a required dll is missing when loading libsimpa.

**Comment by d-cooper** [comment]
Hi! I am trying to find anything from depencencywalker, but I don't know what to look for.
I've noticed that when I load my build of I-SIMPA or one from version 1.3.3 i get different error:

```
>>> import libsimpa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\libsimpa\__init__.py", line 2, in <module>
    from libsimpa import *
  File "C:\Python27\lib\site-packages\libsimpa\libsimpa.py", line 28, in <module>
    _libsimpa = swig_import_helper()
  File "C:\Python27\lib\site-packages\libsimpa\libsimpa.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libsimpa', fp, pathname, description)
ImportError: DLL load failed: Nie mo┐na odnalečŠ okreťlonego modu│u.
```

It says that it can't find some module. Again it works like charm in I-SIMPA console...

**Comment by nicolas-f** [comment]
You have to load the file _libsimpa.pyd in the dependency walker program. It will show you which dll file is missing.

**Comment by d-cooper** [comment]
Ok. I've found it! The boost-system dll was missing. After I copied it from main I-SIMPA folder to _site-packages/libsimpa_ it works well.

Thank you for all the help!

**Comment by nicolas-f** [comment]
Nice. It should fix the issue I have on unit test too on AppVeyor. I make the patch to copy the missing dll

**Comment by nicolas-f** [comment]
I close the issue, as it is fixed on AppVeyor too.
