### ISSUE TITLE
may I translate the chinese version of i-simpa?

### ISSUE THREAD

**Issue by pdwangchao** [Ifsttar/I-Simpa#114]
Hello, everyone!
    I am a PhD. student of Tianjin University in China and very interested in I-simpa. My major is building acoustics and have some Python language experience. May I translate the chinese version of i-simpa?
    I have already made a request on the transfix.
    By the way, thank you very much to write an amazing acoustic software and share it to the world.

**Comment by nicolas-f** [comment]
Hi,

You are welcome to help for the localization of I-Simpa.

You can use PoEdit software to see your translation:
 - Download the .po file from transifex
 - Open it with poEdit and convert it into I-SIMPA/locale/zh_CN/LC_MESSAGES/internat.mo
 - Open I-Simpa

Thanks

**Comment by nicolas-f** [comment]
The language is open. You can now request to join the language as a translator.

**Comment by pdwangchao** [comment]
OK, I will try to use these tools.

**Comment by yipinghan** [comment]
> OK, I will try to use these tools.
Hi , did you finish it?

**Comment by nicolas-f** [comment]
Sorry I forgot to push translations on the last release. I was a bit in a hurry. I will share here I-Simpa with updated translations

**Comment by nicolas-f** [comment]
You can download it here

It is the version of the language update pull request

https://u.pcloud.link/publink/show?code=kZFm2YXZO2Qh7FLate5mEM6J6tvb3YIdaYGX

**Comment by yipinghan** [comment]
> Sorry I forgot to push translations on the last release. I was a bit in a hurry. I will share here I-Simpa with updated translations

Hi 
Thanks for your reply quicly to help me. 
I install your release from that site, but there is no chinese language to choose, actually nothing changed. Is this because I have uninstalled the last release unclearly?  :)

**Comment by nicolas-f** [comment]
It should be ok now. I replaced the files on pcloud

![isimpa_cn](https://user-images.githubusercontent.com/1382241/104293880-d3de1b00-54be-11eb-8ae6-bba9d15f530b.png)

**Comment by yipinghan** [comment]
> It should be ok now. I replaced the files on pcloud

yes, it work out. Thansk for your reply!!  very efficient!
