### ISSUE TITLE
About dialogbox

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#117]
- [x] Box title:  "About I-Simpa" is not translated
- [x] Problem in accentuate character (JudicaA<<l)
- [x] Prefer a left alignment instead of a center alignment
- [x] Prefer (but may be discussed): Name (Institution, Contributor) instead of "Contributor - Name (Institution)

**Comment by nicolas-f** [comment]
I can not change the alignment with the native wxWidgets class. Is it ok to rewrite completely the about dialog in order to do that ?
