### ISSUE TITLE
Desactivate Contextual menu on Directivity file

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#129]
Desactivate "Set the same value" on this element
![image](https://cloud.githubusercontent.com/assets/7996615/23708372/f9621d3e-0415-11e7-842e-ac9bd33ea79a.png)

**Comment by nicolas-f** [comment]
Currently an element does not control the grid menu of its properties. 

I don't understand in which circumstance this menu have to be disabled.

However I could disable "Set the same value" menu item depending on grid cell editor (Float, Int, String, List, File, Color)

**Comment by Picaut** [comment]
Yes, this option should only be available for grids with the same kind of elements (i.e. values or strings or check boxes...). This issue finally concerns all grid elements in I-Simpa.

In addition, for the directivity.
You can copy/paste a directivity as an XML in a text file, but you can not copy/paste a directivity in a User Directivity folder. In this last case, the "Paste" option should not be available.

**Comment by Picaut** [comment]
@nicolas-f Not fully resolved. The menu "Ste the same value">"To the row" is still enabled

![image](https://user-images.githubusercontent.com/7996615/58185901-2fd5a980-7cb4-11e9-9b2a-e1384463209b.png)

**Comment by nicolas-f** [comment]
The fix will disable the option when one of other cell is not of the same type. 
All the columns of the selected cell have the same attribute type (file path), so this option is still enabled (because there is only 1 column in this property)
