### ISSUE TITLE
Global TR value not calculated for TCR (Sabine theory)

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#13]
In TCR results, global value of TR are not calculated (tables present value for each octave band). It could be useful to give a global value (if possible, by an averaging to be found) or to not show "0.00" (this could be replaced by "NC" for "No Calculation").

**Comment by nicolas-f** [comment]
I can technically only set -Inf +Inf or NaN. I've chosen NaN 
``The NaN values are used to identify undefined or non-representable values for floating-point elements``

**Comment by nicolas-f** [comment]
Or maybe using the average absorption value of the room we could give the global reverberation time value.
