### ISSUE TITLE
Is the 'Contour line calculation' option required.

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#131]
In View/Lines, there is an option: 'Contour line calculation'
Can be directly included in 'Contour' option?

**Comment by nicolas-f** [comment]
This is not related to iso contouring of surface receivers.

This function is related to the line view of I-Simpa. As 3d model are composed of triangles, some edge of the triangles can be hidden if two triangle have two common vertices and share the same face normal.

**Comment by Picaut** [comment]
Yes, but should be done at the same time when selecting the Option 'Contour'

**Comment by nicolas-f** [comment]
Sorry I misunderstood, yes, it's true it should be done once, when the user select contour wire mode for the first time.
