### ISSUE TITLE
Could I use all of the CPU capacity?

### ISSUE THREAD

**Issue by pdwangchao** [Ifsttar/I-Simpa#163]
Hi, guys!
When I use the SPPS code to calculate a cubic room, I found that at the beginning, only 50% of the CPU capacity was used, and at the end of the calculation, only 25% was used. 

Could I use all of the CPU capacity?

my CPU is Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz(2401 MHz)
and operation system is Win7 X64 professional SP1

**Comment by nicolas-f** [comment]
Hi,

There is no option to increase the cpu usage of SPPS.

Thanks for feedback
