### ISSUE TITLE
I-Simpa 

### ISSUE THREAD

**Issue by akjain90** [Ifsttar/I-Simpa#191]
I want to use I-Simpa for a small project for which I need following functionalities:
1). Generation of a specific sound signal with a specific bandwidth like chirp or impulse. So I want the functionality to write my own function for the signal.
2). Possibility of placing more then one source with different sound characteristics as mentioned in point 1.
3). visualization of reflections from the wall.

Being new to acoustics and a new user of I-Simpa it will be helpful if someone can give insight on theses points weather these are possible or not and if yes how can i achieve it (may be some tutorial will help).

Thank you.

**Comment by Picaut** [comment]
Dear akjain90,

Currently, the SPPS code inside I-Simpa can only consider sound sources defined by a specific spectrum, not a temporal signal. You can specify the spectrum in the Projet database tree (see http://i-simpa-wiki.readthedocs.io/en/latest/using_spectrum.html) and locate several sources with different spectrum in a room (see http://i-simpa-wiki.readthedocs.io/en/latest/project_window.html#sound-sources).

If you want to visualize reflection on walls, you can add 'particles' in the SPPS code properties (in the Calculation tab) for the parameter 'Number of sound particles per source (display)', for example 10000. Thus, after the calculation, in the Results tab, you can load an animation of sound particles in the room by a right click on the 'particles' file in the corresponding folder.

Best regards.
