### ISSUE TITLE
Complete/improve the translation file

### ISSUE THREAD

**Issue by ronheusdens** [Ifsttar/I-Simpa#192]
Hi,
I have just finished the first tutorial and are enthusiastic about the capabilities of i-simpa. 
I have found however that the English translation is erroneous and often incomplete. Where can I update the translated fields (in what tables are the translated keywords stored)?
I will re-share the improvement with yourself of course!
Thanks for your help.
Ron

**Comment by nicolas-f** [comment]
Hi,

The reference language is english and so can be found in the source code. Other translations can be done on this website https://www.transifex.com/LAE/i-simpa

There is a wiki page about I-Simpa translations process https://github.com/Ifsttar/I-Simpa/wiki/Translate-I-Simpa

Thanks
