### ISSUE TITLE
i-simpa

### ISSUE THREAD

**Issue by Adhara01** [Ifsttar/I-Simpa#217]
Hi.I'm from Brazil.
I need your help with the software I-simpa.
I can not perform the calculations.
Can you help me?I'm sorry for bad English.😅
I had to deliver these analyzed calculations on Monday.😟
Thankss!!

**Comment by Picaut** [comment]
Sorry, we miss this issue. I don't know if you were able to resolve your problem.
The online documentation is here : https://i-simpa-wiki.readthedocs.io/en/latest/
Best
