### ISSUE TITLE
Rhinoceros modeling problem with the surfaces grouping

### ISSUE THREAD

**Issue by LinHsiuMin** [Ifsttar/I-Simpa#223]
Hi,
I use Rhino 6 to build 3D models and export it into 3ds files.
I'm testing how to set the surfaces group like 'Obj_000001[40 41 42...] Obj_000002[50 51 52...]' to the same material group which I can designate easier.
And I found that with a simple geometry, the surfaces group would follow the faces which are "joined" in Rhinoceros. But the problem is when my model goes complicated, it requires all the faces are joined, or the "meshing" won't work out. I have also exported to stl & ply file, and it all requires all the faces to be joined together.
I'm wondering if anyone have face this problem? Or how you usually set the surfaces group.
Thx!

**Comment by nicolas-f** [comment]
Hi,

You can use the online editor Autodesk FormIt

https://app.formit.autodesk.com

Please follow I-Simpa guidelines for scene import:

https://i-simpa-wiki.readthedocs.io/en/latest/import_file_recommandations.html#
