### ISSUE TITLE
Unfold Results tree by default

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#225]
By default, at the first access, the Results tree is not unfold, even when results data are available. Users can think that there is no result. It could be useful if the result data folders could be displayed (at the first access)

![image](https://user-images.githubusercontent.com/7996615/59100095-57b84480-8925-11e9-9f78-9e6e8e6c04cf.png)

![image](https://user-images.githubusercontent.com/7996615/59100124-69015100-8925-11e9-8a98-761be4d823e4.png)

**Comment by nicolas-f** [comment]
Done:
https://github.com/Ifsttar/I-Simpa/commit/57810694b0aa6b2f14d43daa733ac8c039f8e3ee
