### ISSUE TITLE
Importing data form CATT file is not complete

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#227]
When importing data form CATT file (tutorial Elmia Hall), only 1 line on 2 is imported

**Comment by nicolas-f** [comment]
I have 20 materials in I-Simpa when I import Catt file

**Comment by carolgaudeoso** [comment]
It seems like if your .txt file is as the example that comes with the download, it will upload only 1 every 2 materials. When I added the lines following lines after the material and its absorption and scattering:
C:
D:
R:

then, it worked and uploaded everything.

**Comment by nicolas-f** [comment]
Thanks for the feedback, we have to fix the driver.
