### ISSUE TITLE
Travis - how does it affect the program?

### ISSUE THREAD

**Issue by d-cooper** [Ifsttar/I-Simpa#24]
I am not an expert on programming. I would like to know if merging the recent changes (the Travis related things) will change the way my fork of I-SIMPA builds/works. As far as I understand it provides a simpler way of building and testing the application. Does it affect the builds done in Visual Studio? Could you please give me some explanation.

Thanks!

**Comment by nicolas-f** [comment]
Hi,

The travis related files will not affect building.

However we will remove all Visual Studio related files and rely only on CMake. CMake is able to generate Operating System and Compiler specific project files. Then your Visual Studio project files (.sln and .vcxproj) will be generated by CMake. When you will open Visual Studio, you can compile and debug as usual.

**Comment by nicolas-f** [comment]
Travis allow us to deploy a PostGIS install, maybe we can add a special unit test by adding a maven  PostGIS profile.

**Comment by d-cooper** [comment]
Ok, I understand. Thanks for the answer.
Is it possible to make a project using CMake that will work under newer Visual Studio than VS2008 and/or to make the application 64bit?

**Comment by nicolas-f** [comment]
Yes, you just have to select what you want:

![isimpa_cmake](https://cloud.githubusercontent.com/assets/1382241/12846496/42599e46-cc0d-11e5-8c5a-660f460c9dbd.png)

**Comment by d-cooper** [comment]
That's great news. So if I understand it correctly it would need the wxWidgets and Boost build for x64 and with such dependencies it will work?

**Comment by nicolas-f** [comment]
Yes It works already. I compile I-Simpa 64 bits with WxWidgets 3.1 (devel).
There is still much work to do in order to make a complete package and continuous integration of I-Simpa.

**Comment by d-cooper** [comment]
Thank you again for all the answers. I will try to build 64 bit. I hope I will manage to do so.

**Comment by d-cooper** [comment]
Hi,

I've tried to build 64bit version using VS2013, but I failed. The CMake only makes some of the required projects right now and there is no solution containing all the projects newer than for VS2008. If it's not a big problem, could you please tell me how to set everything to make a 64bit version under windows? If it is a problem I will just wait for CMake config to be finished.

Thanks!

**Comment by nicolas-f** [comment]
A CMake project file covering all modules is under the current pull request. It will be merged when it will pass under travis (linux) build.
