### ISSUE TITLE
Upgrade to python 3

### ISSUE THREAD

**Issue by Jee-Bee** [Ifsttar/I-Simpa#241]
I think it is time to replace python 2.7 to python 3.x.
Python 2 will not maintained anymore from 2020-1-1. see also https://pythonclock.org/

**Comment by sss8888** [comment]
I open the software and its error:
13:55:09: Error:OpenGL error 1280
 
how can i do?

**Comment by nicolas-f** [comment]
Hi @sss8888, sorry but your issue is not related to @Jee-Bee issue, please create a new issue and delete your reply

**Comment by Picaut** [comment]
@nicolas-f is-it planned in future release?

**Comment by nicolas-f** [comment]
Its done in dev branch of I-Simpa
