### ISSUE TITLE
Improper display (interface language)

### ISSUE THREAD

**Issue by WuTianming** [Ifsttar/I-Simpa#243]
The English translation is not complete and a large part of the menu is still in French.

The biggest problem is, **some French letters can't be displayed properly** so I have trouble even guessing what the menu means.

My OS (Windows 10) environment language is set to Chinese(simplified) and I suspect that the improper display has something to do with my locale.

![image](https://user-images.githubusercontent.com/16624684/79464051-2ff93900-802c-11ea-8ec9-530ecde64145.png)

I would say that the problem can be solved by either

1. Completing the English translation
2. Checking what is wrong with the text display

the former of which is (imo) simpler.

I downloaded my copy of I-Simpa from https://github.com/ifsttar/i-simpa/releases/tag/v1.2.3 , binary exe file.

**Comment by WuTianming** [comment]
I'm realizing that v1.2.3 is actually a quite old version. Is there a way to get a newer version? (However it's not possible for me to compile the code recently.)

**Comment by WuTianming** [comment]
I also have problem with `sppsNantes.exe` which refused to read the resultant xml file.

```
10:31:48 PM: D:\simpa\I-SIMPA\core\sppsNantes\sppsNantes.exe "C:\Users\wtm\AppData\Roaming\I-SIMPA\current\instance1\report\SPPS\2020-04-16_22h31m46s\config.xml"
10:31:48 PM: sppsNantes.exe :Spps 2.1.2 version 7 juin 2011
10:31:48 PM: sppsNantes.exe :XML configuration file is currently loading ..
10:31:48 PM: sppsNantes.exe :read failed
10:31:48 PM: sppsNantes.exe :XML configuration file has been loaded.
10:31:48 PM: sppsNantes.exe :Scene mesh is currently loading ..
10:31:48 PM: sppsNantes.exe :Unable to read the scene mesh file :
10:31:48 PM: sppsNantes.exe :
```

the xml file has a head saying `encoding="iso-8859-1"`, does this have something to do with my encoding too?

**Comment by nicolas-f** [comment]
Hi,

You can download a more recent version of I-Simpa here:
https://ci.appveyor.com/project/nicolas-f/I-Simpa/build/artifacts

However we still have 3D display issues with Windows 10.

**Comment by WuTianming** [comment]
Unfortunately I have a 32bit windows system which doesn't seem to support all those win64 programs. Does I-Simpa support Linux? I will try under Linux another day.

**Comment by nicolas-f** [comment]
I have built a 32 bits version of I-Simpa a while ago:

https://my.pcloud.com/publink/show?code=kZC9NBkZmTBUAjRHc5FmDAPhIjESG5sk1sMX

Sorry but there is no linux version available for the moment

**Comment by WuTianming** [comment]
Thank you.

The newer version seemed better in that the menu texts are all displayed properly. However as you have said, the 3D display shows a black background and the surfaces are not displayed.

Is there a way for me to get a fully functional version of the software? Or is I-Simpa still in active development so that I have to wait for future releases?

**Comment by WuTianming** [comment]
However I have already solved my original problem (texts are displayed fine in v1.3.4) so I will close this
