### ISSUE TITLE
Unable to achieve results: Can't generate a "report" to visualize particle dispersal map 

### ISSUE THREAD

**Issue by IUISIMBA** [Ifsttar/I-Simpa#25]
**We imported a model, remeshed it, and set up sources/receivers, then ran calculation SPPS. We followed the guidelines provided in the French I-Simpa Handbook under Tutorials. The console reads as follows:**

2:08:26 PM: Loading mesh ASCII file...
2:08:26 PM: Loading ASCII files from mesh generator complete
2:08:26 PM: Total time of meshing: 1324 ms
2:08:26 PM: External code execution
2:08:26 PM: C:\Program Files (x86)\I-SIMPA\core\sppsNantes\sppsNantes.exe "C:\Users\brennmat\AppData\Roaming\I-SIMPA\current\instance1\report\SPPS\2016-02-19_14h08m25s\config.xml"
2:08:26 PM: sppsNantes.exe :Spps 2.1.2 version 7 juin 2011
2:08:26 PM: sppsNantes.exe :XML configuration file is currently loading ..
2:08:26 PM: sppsNantes.exe :Loading of the atmospheric condition..
2:08:26 PM: sppsNantes.exe :Loading of the simulation configuration..
2:08:26 PM: sppsNantes.exe :Loading of the emitter list..
2:08:26 PM: sppsNantes.exe :1 emitters has been loaded.
2:08:26 PM: sppsNantes.exe :Loading of the materials..
2:08:26 PM: sppsNantes.exe :2 materials has been loaded.
2:08:26 PM: sppsNantes.exe :Loading of the punctual receivers
2:08:26 PM: sppsNantes.exe :Loading of the surfaces receivers
2:08:26 PM: sppsNantes.exe :Loading of the obstructions
2:08:26 PM: sppsNantes.exe :XML configuration file has been loaded.
2:08:26 PM: sppsNantes.exe :Scene mesh is currently loading ..
2:08:26 PM: sppsNantes.exe :Opening C:\Users\brennmat\AppData\Roaming\I-SIMPA\current\instance1\report\SPPS\2016-02-19_14h08m25s\mesh.cbin
2:08:26 PM: sppsNantes.exe :Load of the scene mesh file has been completed successfully.
2:08:27 PM: sppsNantes.exe :C:\Users\brennmat\AppData\Roaming\I-SIMPA\current\instance1\report\SPPS\2016-02-19_14h08m25s\tetramesh.mbin
2:08:27 PM: sppsNantes.exe :Tetrahedalization file is empty, the calculation can't be done !
**2:08:27 PM: sppsNantes.exe :Unable to read the tetrahedalization of the scene mesh file, calculation canceled.**
2:08:27 PM: Caluation time: 674 ms
2:08:27 PM: Copy of calculation parameters
2:08:27 PM: Refreshing onglet 'Report'
2:08:27 PM: Error:Failed to load icon from the file '"%1"' (error 2: the system cannot find the file specified.)
2:08:27 PM: Error:Failed to load icon from the file '"%1"' (error 2: the system cannot find the file specified.)
2:08:27 PM: Total time calculation: 2555 ms

**Note the error:Unable to read the tetrahedalization of the scene mesh file, calculation canceled.--- we are unable to find the "ressource" (resource) file under the SPPS calculation report in order to generate a visualization of our data. **

Any ideas?

**Comment by nicolas-f** [comment]
Hi,

Tetgen program may have not run well. Tru running the meshing step separately in order to visualize the tetrahedralisation.

https://github.com/Ifsttar/I-Simpa/wiki/Menu-Simulation

If you agree, you can also send your 3D model to i-simpa[at]ifsttar[dot]fr

**Comment by Picaut** [comment]
Most of time, when you experience problem with tetgen, it is because the 3D model is not "perfect", meaning that the model contains holes, intersecting faces...

I recommend you to read this page:
[(https://github.com/Ifsttar/I-Simpa/wiki/Import-file-recommandations)](https://github.com/Ifsttar/I-Simpa/wiki/Import-file-recommandations)

**Comment by vitorczik** [comment]
I'm having the same problem, even creating a regular rectangular geometry direct from I-Simpa.
Is it possible this issue to be related to the 64 bits OS or to the intel processor?
Do you have any solution ?

**Comment by nicolas-f** [comment]
Hi,

All sound source and receivers must be into the geometry (not placed on walls or outside)

If you still have issues you can send your saved project to our email adress i-simpa[at]ifsttar[dot]fr
