### ISSUE TITLE
Error with results

### ISSUE THREAD

**Issue by skaramroudi** [Ifsttar/I-Simpa#251]
Hello

I created a project based on instructions in https://github.com/Ifsttar/I-Simpa/wiki/Study-of-teaching-room
Everything went ok,but the results had a problem.the results only shows -inf in every parameters can someone help me please?
Thank you

**Comment by nicolas-f** [comment]
You follow this tutorial ?

https://i-simpa-wiki.readthedocs.io/en/latest/tutorial_teaching_room.html

**Comment by skaramroudi** [comment]
> You follow this tutorial ?
> 
> https://i-simpa-wiki.readthedocs.io/en/latest/tutorial_teaching_room.html

Yes I did,

**Comment by nicolas-f** [comment]
Can you share your i-simpa project file ?

**Comment by skaramroudi** [comment]
Sorry for delay,I was covid 19 postivie and couldn't work,came back today and found out that I made mistake following the tutorial,Everything's fine
