### ISSUE TITLE
Mesh problem

### ISSUE THREAD

**Issue by carolgaudeoso** [Ifsttar/I-Simpa#252]
So this geometry is loading and giving no error while meshing, but it doesn't work. The mesh volume is not showing up, so I think there is a problem but I really don't know what the problem should be.
[https://drive.google.com/drive/folders/1ef7m1SJilXviwalEHD94cS4abbqmPFYr?usp=sharing](https://drive.google.com/drive/folders/1ef7m1SJilXviwalEHD94cS4abbqmPFYr?usp=sharing)

**Comment by nicolas-f** [comment]
Its a complex model with intersecting faces and non manifolds edges.

You should try using a CAD software designed for parametric models like FreeCad https://www.freecadweb.org

I tried import your model in freecad but there is at least two edges that causes problems. https://wiki.freecadweb.org/Import_from_STL_or_OBJ

**Comment by carolgaudeoso** [comment]
thank you so much. I will have a look at that!

have a nice day

**Comment by carolgaudeoso** [comment]
Hi, so I've fixed the model using FreeCad just as you said. It has nothing to repair now but tetgen keeps refusing the model. It is detecting self-intersections where it doesn't seem to be one. It is actually hard to find where these surfaces are due to its size. How do I use -d option to detect all self-intersections, as it says in the message?

**Comment by nicolas-f** [comment]
Hi,

You have to check "Test mesh topology" option in mesh properties:

![image](https://user-images.githubusercontent.com/1382241/97269415-ca350780-182d-11eb-9426-e9a9cec3e97b.png)

Faces in error will be colorized. You can find .poly indexes and coordinates in log

**Comment by Picaut** [comment]
This information will be included in the documentation here:
https://i-simpa-wiki.readthedocs.io/en/latest/import_file_recommandations.html
