### ISSUE TITLE
Obtain an array with x, y, z coordinates and sound parameters (suh as intensity)

### ISSUE THREAD

**Issue by STEFANOCARRINO** [Ifsttar/I-Simpa#26]
Hi, can you help me?
I'd obtain a table to export in which the coordinates of points related to results (such as the intensity) can be written. How would I do?
Thank you.

**Comment by nicolas-f** [comment]
Hi,
I have some difficulties to understand your question. Are you talking about file format conversion ? Which point are you talking about ?

regards

**Comment by STEFANOCARRINO** [comment]
I want to obtain a results table mapped on the mesh, like this:
Position               Results
X,Y,Z                     Sound Intensity
Regards

**Comment by nicolas-f** [comment]
Sound level in SPPS are recorded only on specified receivers. You have to create [punctual receivers](https://github.com/Ifsttar/I-Simpa/wiki/Punctual-receivers) or [surface receivers ](https://github.com/Ifsttar/I-Simpa/wiki/Surface-receivers)

**Comment by STEFANOCARRINO** [comment]
Thank you so much Nicolas. A last question, there are some tutorials? Those of site are incomplete.

**Comment by nicolas-f** [comment]
There is a french manual in the I-SIMPA install folder:
`\I-SIMPA\documentation\manuel_I_Simpa.pdf`

You can find complete tutorial at the end of the document.

**Comment by STEFANOCARRINO** [comment]
Hi Nicolas,
can I-Simpa work in /batch mode?
Regards

**Comment by STEFANOCARRINO** [comment]
And what parameters are tabled in fusion.gabe file?

**Comment by nicolas-f** [comment]
`can I-Simpa work in /batch mode?`

It depends on what you want to do. I-Simpa and Spps are two independent software. 

You can
- Run SPPS by providing the same files generated by I-Simpa.
- Use the script "Liste de travail" in order to run consecutive computations using multiple project files. (right click on computation core then "Liste de travail"/"Ajouter le calcul", save your project then save as elsewhere..)
- Use the embedded scripting language in I-Simpa in order to automatically update input parameters and launch SPPS.

`And what parameters are tabled in fusion.gabe file?`
It is EDT, you can switch the extracted parameter by editing this file that create fusion.gabe:
I-SIMPA\UserScript\recp_res_tool\__init__.py

**Comment by STEFANOCARRINO** [comment]
how can I edit an change _init_.py in I-Simpa?

**Comment by STEFANOCARRINO** [comment]
Hi Nicolas,
I've obtained succesfully that I wanted editing *py file. Another question, there is a possibility to run the script for the results of Théorie classique??

**Comment by nicolas-f** [comment]
The results of classical theory are not the same as SPPS.Sound level is not time dependent and EDT and TR are computed for the whole scene in classical theory.

**Comment by STEFANOCARRINO** [comment]
What happens if I don't define any volume for receivers in a computation with SPPS?

**Comment by nicolas-f** [comment]
No particles will cross the receivers sphere, then no results at all.

**Comment by STEFANOCARRINO** [comment]
Hi Nicolas,
why the results of a receiver are different from those of a surface at the same point and in the same conditions? In particular on the same point I read 138 dB (SLP) by punctual receiver and 130 dB by surface receiver.
Thank you very much!

**Comment by STEFANOCARRINO** [comment]
*SPL

**Comment by nicolas-f** [comment]
Thanks for feedback.

Please make an issue thread for each issue.

I will make a separated issue for this question.

**Comment by Picaut** [comment]
For both calculations, the method is different:
- for a surface receiver, the SPL is calculated by summing the energy of each sound particle passing through a **surface element**;
- for a volume receiver, the SPL is calculating by summing the energy of each sound particle passing through a **volume element**;
In function of the size of the volume receiver, this can imply differences between the surface receiver.

My opinion is that:
- the volume receiver is much more relevant than the surface receiver for pressure values (SPL).
- the surface receiver is more relevant for intensity values (SIL)

However we will try to study with more detailed, the relation between sruface and volume receivers.

**Comment by nicolas-f** [comment]
Linked with #29
