### ISSUE TITLE
Problems with pop menu on Orientation point and Position for punctual receviers

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#261]
**Describe the bug**
The "Link to the source" option on "Orientation point" for a punctual sound source not working
Additionally, there is an unwanted option on "Position", called "Please choose the source".

**To Reproduce**
1. Select an punctual receiver
2. Right click on "Position" or "Orientation point" to see the option

**Expected behavior**
Selection a source for orienting the receiver
No "Please choose the source" on "Position"

**Screenshots**
See screenshots

**Desktop (please complete the following information):** See 'About I-Simpa' for the Version and build
 - OS: WIndows 10
 - Version: 1.3.4 
 - Build date: Built on 2020-12-04T09:10:49

**Additional context**

![image](https://user-images.githubusercontent.com/7996615/101352159-fd899e00-3891-11eb-877f-a059e6ee278a.png)

![image](https://user-images.githubusercontent.com/7996615/101351638-28272700-3891-11eb-9107-67b87474f9f2.png)

**Comment by nicolas-f** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\I-SIMPA\SystemScript\preceiv_sourceTracker\__init__.py", line 158, in LinkWithSourcePosition
    selected_sourceid=self.AskUserToSelectASource()
  File "C:\Program Files\I-SIMPA\SystemScript\preceiv_sourceTracker\__init__.py", line 139, in AskUserToSelectASource
    srcLst.sort()
```

**Comment by Picaut** [comment]
Is-it done?

**Comment by nicolas-f** [comment]
yes
