### ISSUE TITLE
Strange behavior for atmospheric implementation

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#263]
**Describe the bug**
Using SPPS, and considering atmospheric absorption during propagation, the number of sound particles absorbed due to air absorption should be increased with the frequency.

**To Reproduce**
1. Create a simple geometry, with a sound source
2. Compute SPPS calculation with atmospheric absorption checked
3. Open 'SPPS particle statistics' file
4. See the evolution of the number of sound particles absorbed by the atmosphere

**Expected behavior**
This number of sound particles absorbed by the atmosphere should increase with frequency. For low frequency, this behavior is questioning

**Screenshots**
See screenshot for an example

**Desktop (please complete the following information):** See 'About I-Simpa' for the Version and build
 - OS: Windows 10
 - Version : I.3.4
 - Build date: Built on 2020-12-04T09:10:49

**Additional context**
Seems we obtain the same results with older version of I-Simpa (2018)

![image](https://user-images.githubusercontent.com/7996615/101506018-3f3f4500-3975-11eb-9b1b-993bdc8f0d7c.png)

**Comment by Picaut** [comment]
Here another example, for a perfectly specular room (no absorption, no diffusion).
See the '.proj' file.
Very strange results

![image](https://user-images.githubusercontent.com/7996615/101510612-706e4400-397a-11eb-8f90-f9a0f32d7e32.png)


[Validation_atmospheric_absorption_simple.zip](https://github.com/Ifsttar/I-Simpa/files/5660450/Validation_atmospheric_absorption_simple.zip)

**Comment by nicolas-f** [comment]
The probability of atmospheric apbsorption is computed here:
https://github.com/Ifsttar/I-Simpa/blob/master/src/spps/CalculationCore.cpp#L57

This probability is computed here:
https://github.com/Ifsttar/I-Simpa/blob/v1.3.3/src/lib_interface/data_manager/base_core_configuration.cpp#L121

Maybe the cause is the usage of float type instead of double. I will check this.

**Comment by nicolas-f** [comment]
You are in energetic mode. Particles does not disappear according to atmospheric absorption, they disappear if the energy remaining after 2 seconds of propagation is below a threshold defined in SPPS settings.

In your example, this threshold is reached starting with 8000 Hz.

**Comment by Picaut** [comment]
Yes, you are right for the second example. But for the first example, I have also considered the Energetic option. How particles can be absorbed by the atmosphere. Is due to the extinction of the energy at -10^5 ?
[Validation_atmospheric_absorption.zip](https://github.com/Ifsttar/I-Simpa/files/5679589/Validation_atmospheric_absorption.zip)

**Comment by nicolas-f** [comment]
Even if the materials have absorbed the majority if the energy of the particle but at the last step the atmospheric absorption put the energy below the set extinction value so it is marked as absorbed by the atmosphere.

**Comment by Picaut** [comment]
OK thank you. So this a bug, but the bug is me !
I close this comment.
