### ISSUE TITLE
How to add MD code in Isimpa

### ISSUE THREAD

**Issue by skaramroudi** [Ifsttar/I-Simpa#272]
Hello everyone ,so I'm so bad at working with codes and I need to make a comparison between MD code and SSPS code, can someone please show me how can I add MD code to Isimpa so it works like SPPS and TCR work?

**Comment by nicolas-f** [comment]
Hi,

You have to copy this folder into the core subfolder of I-Simpa:
https://github.com/Ifsttar/I-Simpa/tree/master/currentRelease/ExperimentalCore/md_octave
And copy this folder in the UserScript folder of I-Simpa
https://github.com/Ifsttar/I-Simpa/tree/master/currentRelease/ExperimentalScript/md_octave

Then you have to install Octave software. When creating a new project, you will see the new computation core.

**Comment by nicolas-f** [comment]
You have to install h5py also:

https://github.com/Ifsttar/I-Simpa/wiki/Add-Python-packages-in-I-Simpa

**Comment by nicolas-f** [comment]
Don't hesitate if you have any issues

**Comment by skaramroudi** [comment]
> Hi,
> 
> You have to copy this folder into the core subfolder of I-Simpa:
> https://github.com/Ifsttar/I-Simpa/tree/master/currentRelease/ExperimentalCore/md_octave
> And copy this folder in the UserScript folder of I-Simpa
> https://github.com/Ifsttar/I-Simpa/tree/master/currentRelease/ExperimentalScript/md_octave
> 
> Then you have to install Octave software. When creating a new project, you will see the new computation core.

thank you so much,just one thing,how I can i find Octave software?

**Comment by skaramroudi** [comment]
And sorry that I'm such an amateur, can you show me how to download the folders you told me?

**Comment by nicolas-f** [comment]
Octave
https://www.gnu.org/software/octave/download
Download module
https://github.com/Ifsttar/I-Simpa/archive/v1.3.4.zip

(find subfolder in the zip file)
