### ISSUE TITLE
problème affichage dernière version 1.3.4 dans Windows 10

### ISSUE THREAD

**Issue by MaximeThepaut** [Ifsttar/I-Simpa#273]
Bonjour Nicolas

Suite à l'installation de la dernière version de I SIMPA 1.3.4, j'ai un problème d'affichage (cf image). (Je suis sur Windows 10)
![bug affichage I SIMPA](https://user-images.githubusercontent.com/81325102/112364919-55300600-8cd7-11eb-8f17-0b4dbfcef261.png)

**Comment by nicolas-f** [comment]
Bonjour,

Ah oui c'est original. Peut être mettre à jour les drivers vidéo et redémarrer I-Simpa ?

**Comment by pierromond** [comment]
> https://www.malekal.com/mettre-a-jour-pilotes-carte-graphique-windows-10/

**Comment by MaximeThepaut** [comment]
OK merci. je regarde ça

**Comment by MaximeThepaut** [comment]
Je viens de mettre à jour le pilote de ma carte graphique NVIDIA mais en redémarrrant I-SIMPA, le bug d'affichage est toujours là

**Comment by nicolas-f** [comment]
Peut être avec le mode compatibilité Windows 7 ?

https://www.dummies.com/computers/operating-systems/windows-7/how-to-make-an-older-program-run-in-windows-7/
