### ISSUE TITLE
Get SPL over time results from the .recp file

### ISSUE THREAD

**Issue by dfguooo** [Ifsttar/I-Simpa#279]
I am interested in using i-simpa and SPPS to study some echo-timing-related problem in a room. I notice that the SPL over time is available in the results of punctual receivers, as shown in the fig below. I think these SPL results contains the timing info of the echoes, please correct me if I am wrong.

![image](https://user-images.githubusercontent.com/71545825/121894701-059b2c80-cd52-11eb-9672-e0498043e481.png)

My silly question is how can I get these data from the "Sound level.recp" file in the folder?

Btw, is it possible today to directly obtain the room impulse response from i-simpa?

Thanks!

**Comment by dfguooo** [comment]
Hi Nicolas, thank you for your prompt reply!

For current stage, I can save the data by right-clicking in i-Simpa. Later I might want to extract the data from the recp file for data processing without i-simpa GUI. Is it tricky to do so?

**Comment by nicolas-f** [comment]
Without the GUI you can use the libsimpa library. Its a C/Python library. You can find an example here:

https://github.com/Ifsttar/I-Simpa/blob/master/src/python_bindings/samples/spps_conversion_resultats.py

The python interpreter is on the I-Simpa install folder

**Comment by dfguooo** [comment]
Noted with thanks! I will look into it
