### ISSUE TITLE
Setting the scale for color maps

### ISSUE THREAD

**Issue by Clarity-Acoustical** [Ifsttar/I-Simpa#283]
**Is your feature request related to a problem? Please describe.**
When I graph a color map on a surface receiver (i.e., C50>Load Animation>Cumulating Sound Level), the scaling of the graph varies wildly.  Sometimes the provided scaling is useful, often it is not.  Being unable to control the scaling makes it very difficult to compare graphs from one simulation to another; color maps that are essentially identical can wind up looking very different from each other.

**Describe the solution you'd like**
I'd like it if there was a simple way to set the upper and lower limits of the scaling of the color map.  That way apples-to-apples comparisons can be made.

**Additional context**
![image](https://user-images.githubusercontent.com/86608807/125334366-b0871200-e321-11eb-98b1-585ef42a28f1.png)
![image](https://user-images.githubusercontent.com/86608807/125334424-be3c9780-e321-11eb-88a2-8f0da16072e4.png)

**Comment by Picaut** [comment]
Just Right click on the file in the Result tree and select 'Properties", than changes 'Maximum value' and 'Minimum value'
![image](https://user-images.githubusercontent.com/7996615/148064800-6f4f8889-b532-448c-8800-838b8d7edf3c.png)
