### ISSUE TITLE
RT calculation

### ISSUE THREAD

**Issue by pbasilio** [Ifsttar/I-Simpa#34]
I've been messing around with I-Simpa again, but, this time, I'm getting odd results when adding absorption to a surface, basically what I've done is to add absorption to the ceiling of a room, and the RT should be reduced, but, the results I'm getting from the SPPS calculation are not what I expected them to be. The results are the same when using the un-modified version of I-Simpa and the diffusion corrected I-Simpa. Maybe I'm doing something wrong... The results are the following:

![i-simpa rt question](https://cloud.githubusercontent.com/assets/16143796/15269912/a8269924-19c2-11e6-97ed-712598baa109.png)

The graphs that say "original" are the ones of the room with the original surfaces of the room (plasterboard and concrete) and the ones that say blackacoustic is the material that I'm using for the absorption on the ceiling. 

I don't get why I'm getting a small difference with absorption when the calculation is done with SPPS. 

The results are very similar when using:

*energetic or random calculation methods.
*modified or unmodified I-Simpa.
*with 150,000 or 5000000 sound particles.

I know I'm missing something... just don't know what 

thanks

**Comment by d-cooper** [comment]
Indeed it looks odd. Could you attach the I-SIMPA project file?

**Comment by pbasilio** [comment]
[Estudio TV azul83_simple.zip](https://github.com/Ifsttar/I-Simpa/files/264704/Estudio.TV.azul83_simple.zip)

thanks!

**Comment by d-cooper** [comment]
The problem you have is 0 diffusion coefficient combined with cuboid geometry. Some rays are bouncing between side walls never/rarely hitting the ceiling. When I set diffusion coefficient 0.1 for all materials the RT for 1000Hz reduced to 1.1s. I was thought to consider 0.1 diffusion as minimum for all materials.

**Comment by pbasilio** [comment]
d-cooper to the rescue! haha :)

Well... I normally do set the diffusion coefficient to .1 but, when I saw the txt example file in the I-Simpa folder without the values for diffusion, I just did it the same way, I should have known better haha.


Thanks!

**Comment by pbasilio** [comment]
As much as I want to work with I-Simpa, there is always something wrong...

Now sppsnantes always crashes, even if the meshing gets done, sppsnantes always crashes, the only way to make it work is to do the manual scene inside I-Simpa, I've tried all the available export configurations... 

The last time i was working with i-simpa, the meshing was the one giving me hard time, but, if the meshing was done properly (like drawing lines across surfaces) the calculation was successful, now any configuration other than the manual scene gives me a hard time.

I'm using sketchup 2016, windows 10 and exporting to 3ds, any ideas?  :(

**Comment by nicolas-f** [comment]
Hi,

Please send a zipped file to i-simpa[at]ifsttar[dot]fr containing the result folder where the mesh is done and spps crash. Thanks

Tetgen (mesh program) require a closed non-overlapping model as described here:
http://wias-berlin.de/software/tetgen/plc.html

**Comment by pbasilio** [comment]
I sent an email to that account... thanks. :+1:

**Comment by nicolas-f** [comment]
Hi,

We will looking at it. Thanks

**Comment by nicolas-f** [comment]
Hi,

The sound source must be in the scene, you put in in the wall.

We still have to detect if the sound source is in collision with a wall, inform the user then cancel the computation.

**Comment by pbasilio** [comment]
I've tried it in many different ways, the file that i sent was the least modified (leaving parameters as they appear) but... it doesn't really matter if i put the sound source in the wall, or in different positions inside the scene, I thought that the issue could be the related to the imported materials, but it doesn't make a difference, the calculation crashes and doesn't do anything even if the meshing gets done properly, attached to this email you can find a screenshot of the issue.
thanks
              

Date: Thu, 26 May 2016 01:05:11 -0700

**Comment by pbasilio** [comment]
![i-simpa issue](https://cloud.githubusercontent.com/assets/16143796/15628104/8686724e-24ad-11e6-9b3d-c3a5de50c1af.png)

It doesn't make a difference if i put the sound source in the wall or inside the scene, the issue remains the same.

Thanks.

**Comment by nicolas-f** [comment]
Hi,

SPPS does not have write access on folder C:\Users\Pirrus\AppData\Roaming\I-SIMPA

Maybe this folder has been set to Administrator only for unknown reason.

http://answers.microsoft.com/es-es/windows/forum/windows_8-security/la-operaci%C3%B3n-solicitada-requiere-elevacion/30260e3b-5e0d-41aa-97f1-4c1433066f0c?auth=1

**Comment by pbasilio** [comment]
It works now, my I-Simpa was actually running with administrator compatibility, but I needed to put a password to my user to actually make it work again (don't know why... before it worked without password).


Thank you very much!

**Comment by pbasilio** [comment]
Hello, it's me again haha



have you had issues with i-simpa lately? I've been working with your corrected version of the sppsnantes.exe, but all of the sudden it crashes whenever i try to use it, i can only use the standard installation of the i-simpa. I've even tried formatting my PC, and i get the same issue.


I remember that you were comparing CATT acoustics with i-simpa in your thesis, how did it compare?



Thanks!


________________________________
De: d-cooper <notifications@github.com>
Enviado: sábado, 14 de mayo de 2016 04:07 p. m.
Para: Ifsttar/I-Simpa
CC: pbasilio; Author
Asunto: Re: [Ifsttar/I-Simpa] RT calculation (#34)


The problem you have is 0 diffusion coefficient combined with cuboid geometry. Some rays are bouncing between side walls never/rarely hitting the ceiling. When I set diffusion coefficient 0.1 for all materials the RT for 1000Hz reduced to 1.1s. I was thought to consider 0.1 diffusion as minimum for all materials.
