### ISSUE TITLE
Verbose mode of SPPS

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/I-Simpa#36]
Add a (disabled by default) verbose mode to SPPS computation core.

If verbose mode is disabled only vital information are printed. (Main progression event, warnings and errors)

**Comment by austil** [comment]
https://github.com/austil/I-Simpa/commit/c90ccd0e2abd3a838ac457cd1421ea3eef4a6581
Need more details on what to display or not.

**Comment by nicolas-f** [comment]
If not in verbose mode. Hide all messages except progression (#XX), and std::cerr

**Comment by austil** [comment]
https://github.com/austil/I-Simpa/commit/2386aef36279b2228083ad57774d6e1b64f2bc8d
