### ISSUE TITLE
Move data_manager, input_output and tools folders?

### ISSUE THREAD

**Issue by d-cooper** [Ifsttar/I-Simpa#38]
I am implementing new calculation codes based on SPPS. 
Because all codes share some tools I think it may be good to move folders with tools, data manager and input output for SPPS to some folder in main src directory, so they are not bounded to certain calculation code, but generally available. Then to make changes it would just require making a derived class with changes only.

I know it can be done without moving folders, but I think it will make the solution clearer.

**Comment by nicolas-f** [comment]
LibInterface is the shared code between computation codes and I-Simpa.

Core configuration of SPPS add spps specific parameters over lib interface generic parameters.

Tools folder contain particle distribution for sound source. If on the future we will provide other computation core based on particle we will migrate them. At the moment, there is no reason to do this with the master repository.

**Comment by d-cooper** [comment]
Ok. I understand.

The reason why I mentioned that is now I have two more calculation cores based on SPPS which share most of the functions from reportmanager and all tools sometimes with small modifications.

I can either copy those files to individual calculation core folders, but when you make changes in any of these files I would have to make changes manually to copies or make derived classes what would require including files from /spps/... to other calculation cores what may seem unclear.

**Comment by nicolas-f** [comment]
You can make an intermediate project between all spps derived and lib interface for shared code.

**Comment by d-cooper** [comment]
Thank you for the answer.
