### ISSUE TITLE
New directivity options don't show for old projects

### ISSUE THREAD

**Issue by wbinek** [Ifsttar/I-Simpa#42]
I've compiled the new version of I-SIMPA and I've noticed that new directivity options doesn't show for old projects.

**Comment by nicolas-f** [comment]
Should be fixed in https://github.com/Ifsttar/I-Simpa/pull/43

Thanks for report

**Comment by d-cooper** [comment]
I've merged the last changes but it still doesn't work.
There is no "Directivity balloon" element on directivity mode list and no "Directivity balloon" tree for each source.
There is also no "Directivities" in project database.

For new projects everything is fine.

**Comment by wbinek** [comment]
Tested. It seems to be ok now.
