### ISSUE TITLE
I-Simpa.exe will not run in Windows 10

### ISSUE THREAD

**Issue by SethHollandsworth** [Ifsttar/I-Simpa#47]
Hello,
I have tried to run the executable file in compatibility mode for windows 7 and regularly in Win10 but it still throws up an error before the language selection menu and crashes after the language is selected. Here are some screenshots of the errors.

 Any help would be much appreciated. 

Thanks 
-Seth

![i-simpa error3](https://cloud.githubusercontent.com/assets/22140568/18423777/07e16940-7876-11e6-9e2a-3af95840605b.JPG)
![i-simpa error2](https://cloud.githubusercontent.com/assets/22140568/18423778/07e5f5b4-7876-11e6-8610-9351199efacb.JPG)

**Comment by austil** [comment]
Work for me without compatibility mode.
Are your graphic driver up to date ?
Did you donwloaded the latest release (1.3.1, [from github](https://github.com/Ifsttar/I-Simpa/releases/tag/v1.3.1), not the website) ?

**Comment by SethHollandsworth** [comment]
Redownloaded from github and it works now. thanks for the help and the link

**Comment by nicolas-f** [comment]
@austil Hello and Thanks for the help. I'm glad that this issue are resolved.
