### ISSUE TITLE
Number of decimal after the comma for data tables

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#60]
When displaying acoustics parameters, Schroeder's curves... or any table containing data, limit the number of decimal after the comma.
- for dB or equivalent: 1 number after comma
- for ms or s: 1 or 2
- for %: 1 

For example:

![image](https://cloud.githubusercontent.com/assets/7996615/20010534/bdaf625c-a2a8-11e6-8dbf-d716b1e80891.png)

![image](https://cloud.githubusercontent.com/assets/7996615/20010561/ce409154-a2a8-11e6-9c10-2eee5b4ebc8f.png)

**Comment by nicolas-f** [comment]
I can round off the value at the end of the computation. But not recognize the kind of information and change the display accordingly. Is it ok ?

**Comment by Picaut** [comment]
OK.
