### ISSUE TITLE
Results in the 'Sound level per source.recp' file

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/I-Simpa#63]
This file give the sound level per source. It seems OK:
![image](https://cloud.githubusercontent.com/assets/7996615/20012499/ddef1e66-a2af-11e6-910d-96317707a8b0.png)

However, as it uses the same methods as for a the classical representation for a punctual receiver, it shows also the 'Spectrum' charts, as well as, the Schroeder' curves. 
![image](https://cloud.githubusercontent.com/assets/7996615/20012580/24c8aea6-a2b0-11e6-869f-67d00292b1f9.png)
![image](https://cloud.githubusercontent.com/assets/7996615/20012596/2fdd1994-a2b0-11e6-9f6b-1118071aa626.png)

However, there is only one column for each source, which gives a no relevant charts.

Proposal:
- remove the tab with Schroeder' curves
- in addition to the 'global spectrum', display the spectrum for each source (if N sources, displays N bars for each frequency band)

**Comment by nicolas-f** [comment]
Fixed
