### ISSUE TITLE
impulse response

### ISSUE THREAD

**Issue by sergiofrias** [Ifsttar/I-Simpa#65]
Is there any way to export a impulse response(.wav)?

thank you.

Sérgio

**Comment by nicolas-f** [comment]
Hi,

No sorry, SPPS has no auralisation functionality yet.

Best regards,

**Comment by dfguooo** [comment]
> Hi,
> 
> No sorry, SPPS has no auralisation functionality yet.
> 
> Best regards,

Hi Nicolas, is there any way now to obtain the impulse response?
