### ISSUE TITLE
Check compatibility between 1.3 and 1.2

### ISSUE THREAD

**Issue by FoyCedric** [Ifsttar/I-Simpa#66]
the project created with the 1.2.3 can't be run with the version 1.3.1. It seems that the "sppsNantes" has been replaced by the name "spps" in the project_config.xml.

**Comment by nicolas-f** [comment]
Its weird, this property should be updated here:
https://github.com/Ifsttar/I-Simpa/blob/v1.3.1/src/isimpa/data_manager/tree_core/e_core_sppscore.h#L129

I hope to fix this next week.
