### ISSUE TITLE
Information during processing can be misunderstood

### ISSUE THREAD

**Issue by FoyCedric** [Ifsttar/I-Simpa#69]
Calculation is in progress and will finish, but information is given and mentions that calculation is not responding. This can be misunderstood by users

![capture_wait](https://cloud.githubusercontent.com/assets/8665758/20141578/483e1a8a-a691-11e6-9f46-faf36f18018c.PNG)

**Comment by nicolas-f** [comment]
Crash may be closely related to I-SIMPA not responding while executing external programs (tetgen or spps).

I'm working on this.

 I could even not set this dialog [modal](https://en.wikipedia.org/wiki/Modal_window) (user can still doing things in I-SIMPA while calculation occur).

**Comment by nicolas-f** [comment]
Spps update progression with a more regular pattern now
