### ISSUE TITLE
Acoustic parameters (C50,C80, D50 etc.) calculation bug

### ISSUE THREAD

**Issue by wbinek** [Ifsttar/I-Simpa#7]
Function GetSumLimit() in projet_calculation.cpp calculates from time=0, whereas all parameters should be calculated starting from time when direct wave approaches the receiver.

I've made a temporary solution at:
https://github.com/d-cooper/I-Simpa/commit/827530d679d8ea1ccf1829339c237fe46bfd0fef

**Comment by nicolas-f** [comment]
Thanks for feedback.

We have to fix this issue by changing the fromTime value. (without copying array)

**Comment by nicolas-f** [comment]
After reading again the code:

The implementation follow the `ISO 3382:1997(F)`. The reverberation time TR30 is computed using the regression on a Schroeder curve from -5db to -35db. 

The variable `wxFloat32 fromTime` is the time when the value is -5 dB inferior than the higher value of the Schroeder curve.

**Comment by nicolas-f** [comment]
All this post-processing code will be moved into lib_interface and included into the automated unit test framework.

**Comment by d-cooper** [comment]
The RT calculation is ok. The bug is in energetic parameters calculation (mainly C, and D). The integration should start when the impulse arrives to the receiver not from t=0.

**Comment by d-cooper** [comment]
If you look at for example [projet_calculation.cpp](https://github.com/Ifsttar/I-Simpa/blob/501886cb4d54042f70d570f66d0f0c342c7f0a26/src/isimpa/data_manager/projet_calculation.cpp) in C param calculation there is:

>wxFloat32 wj_CurrentFreq=GetSumLimit(idFreq,0.f,te,timeTable,tab_wj)/GetSumLimit(idFreq,te,-1.f,timeTable,tab_wj);

The problem is that instead of starting integration from fixed 0 it should start when direct sound approaches the receiver. It can be changed in parameter calculation funcition or GetSumLimit method. 
This applies to all energetic parameters.

**Comment by nicolas-f** [comment]
Yes sorry, I was focused in RT and EDT. I reopen the issue and I will fix it by updating 

Compute_ST_Param
Compute_C_Param
Compute_D_Param
Compute_TS_Param
Compute_LEF_Param
Compute_LF_Param
Compute_LFC_Param
Compute_LG_Param
Compute_G_Param

**Comment by Picaut** [comment]
I have try to validate this modification. However, I obtained NaN or °Inf values for all parameters (except reverberation parameters).
Need to verify step by step the calculation, in  debug mode.

**Comment by Picaut** [comment]
May be a problem in this function. Is-it for finding the time step of direct field? `lastdb `should not be updated at each time step?
Time step of the direct field (if exists) could be estimated simply by calculating the distance from source;
If no direct field ?

https://github.com/Ifsttar/I-Simpa/blob/dca3a488d558d3756fb2a90a0f52877e2238c9bd/src/isimpa/data_manager/projet_calculation.cpp#L114-L126

**Comment by nicolas-f** [comment]
Yes it could be that. GetTimeDecay should return the time before the noise level is decaying .

**Comment by Picaut** [comment]
Are you sure it finds the time step of the direct field (or a valid change/increasing of energy)?

**Comment by nicolas-f** [comment]
With I-Simpa in dev branch I have this:

![isimpa](https://user-images.githubusercontent.com/1382241/101137855-bd1aed80-360f-11eb-800a-323d6db195ef.png)



What is the timestep in spps ?
[issue_7.zip](https://github.com/Ifsttar/I-Simpa/files/5641313/issue_7.zip)

**Comment by nicolas-f** [comment]
ok, there is an issue when sound power received is < 0 dB. I will try to fix that

**Comment by Picaut** [comment]
May be that results are correct. I have prepared a I-Simpa project with the possibility to compare results with expected values for C, D...

**Comment by Picaut** [comment]
I have compared SPPS and expected theoretical results for 100% diffusing room, in many room size (verifying also the effects of the Time Step and distance from source). It seems that the procedure for calculating the clarity C80 within I-Simpa seems correct. It probably needs further validation with measurements or other reference data, but it seems quite acceptable for now.

![image](https://user-images.githubusercontent.com/7996615/101354453-7dfdce00-3895-11eb-80c5-efc361ba5fc1.png)
