### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll missing

### ISSUE THREAD

**Issue by chojny** [Ifsttar/I-Simpa#72]
Hi, im getting this issue everytime i try to run I-SIMPA software, i tried with different versions - still no effect. Maybe you have any sollution for this problem?

**Comment by nicolas-f** [comment]
Hi,

What is the version of your operating system ? Have you installed the [isual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-gb/download/details.aspx?id=48145) ?

Regards,

**Comment by nicolas-f** [comment]
This is the same issue I think https://helpx.adobe.com/creative-cloud/kb/error_on_launch.html

**Comment by nicolas-f** [comment]
Fix with last version and with the install of redist 2015
