### ISSUE TITLE
Recover project file

### ISSUE THREAD

**Issue by pbasilio** [Ifsttar/I-Simpa#73]
Hello, I've been working on I-Simpa but, apparently my project file has been corrupted, any other project loads just fine as expected, but this particular project, leaves the same project even when you are supposed to be on the new loaded project, I'll explain it better....

case 1 - Open I-Simpa>loads empty project>open corruptedfile.proj>layout still empty (even though it didn't show an error on screen while loading the project) but showing the proper name of the file at the top with an * at the end

case 2 - Open I-Simpa>opens up with anyother.proj (loads just fine)>open corruptedfile.proj>layout and scene is still the anyother.proj with the corruptedfile.proj name on top with an * (as if the file was unsaved)

log:
2:30:05 AM: Error:can't open file 'C:\Users\Pirrus\AppData\Roaming\I-SIMPA\current\instance1\projet_config.xml' (error 2: el sistema no puede encontrar el archivo especificado.)
2:30:05 AM: Loading project: Antigua Acoustics - 92m2 Ceiling Blackacoustic + 36 panels.proj

the file size of the project is 2.5GB, therefore it does have data in it...

Is there a way to restore the project or anything? I cannot remember doing anything unusual that could have had caused the issue. I've also tried to open the project on another computer without any luck.

Thanks.

**Comment by nicolas-f** [comment]
Hi

The .proj file is a zip file.

projet_config.xml contain all properties visible in the left trees.

If projet_config.xml is missing, then you have lost this project configuration, but not the results (report subdirectory).

You can create a new project and copy the report folder into %APPDATA% then in folder isimpa\current\instance1

In I-SIMPA refresh the result tab to see the copied files.

**Comment by pbasilio** [comment]
Perfect, copy-paste of the report works great. Also, I tried to copy-paste the project_config.xml and it worked at least to know the positions of sources and receivers and the parameters used for the surfaces, the only thing missing are the actual surfaces, but the important parts were recovered, thanks!

**Comment by nicolas-f** [comment]
I forgot to say that a backup of projet_config.xml is copied on each result folder (under the computation date). You can copy this file to have the project config at this date.

**Comment by pbasilio** [comment]
Perfect, I'll try that too. Also, I have been trying to get the latest release of i-simpa but i think the link is not working, do you know if there's a mirror to download it?

Thanks

On Dec 8, 2016 01:05, nicolas-f <notifications@github.com> wrote:

I forgot to say that a backup of projet_config.xml is copied on each result folder (under the computation date). You can copy this file to have the project config at this date.

**Comment by nicolas-f** [comment]
Yes there is an error in the download link.

I don't know which version you use but we have some blocking issues with the last releases, so you should stick with your version. I'm working on a new version that fix crash bug when executing external programs.

**Comment by pbasilio** [comment]
Perfect, I'll try again later.

I am using i-simpa v1.2.2 and was hoping to try the directivity option in the new release, is there a way to simulate the directivity of a sound source (like a speaker) with this version?

And... I don't know if this has been corrected yet (haven't seen any issue ticket of this on github neither), but in the 1.2.2 version when you change surfaces to an already made group from the scene, it doesn't update the surface area ie. Two scene groups, let's say concrete and plasterboard, in the first try you group all the walls to plasterboard and ceiling and floor to concrete, but then you change one wall to the concrete surface group and the surface area stays the same, it doesn't update the area.

Thanks!

On Dec 8, 2016 01:29, nicolas-f <notifications@github.com> wrote:

Yes there is an error in the download link.

I don't know which version you use but we have some blocking issues with the last releases, so you should stick with your version. I'm working on a new version that fix crash bug when executing external programs.

**Comment by pbasilio** [comment]
Hello, sorry to bother you again (i don't want to open a new ticket), i am aware of the scatering issue in i-simpa, and a user once provided with the corrected sppsnantes.exe but all of the sudden it stopped working, i thought it was my OS, but i've tried a new OS installation and i get the same issue, it crashes when the sppsnantes runs, is there another way to fix this issue?


________________________________
De: nicolas-f <notifications@github.com>
Enviado: jueves, 8 de diciembre de 2016 02:29 a. m.
Para: Ifsttar/I-Simpa
CC: pbasilio; State change
Asunto: Re: [Ifsttar/I-Simpa] Recover project file (#73)


Yes there is an error in the download link.

I don't know which version you use but we have some blocking issues with the last releases, so you should stick with your version. I'm working on a new version that fix crash bug when executing external programs.

**Comment by nicolas-f** [comment]
Hi, the scattering issue patch has been merged a while ago so it is not necessary to use old spps version.

**Comment by pbasilio** [comment]
So, i just download the latest version on github and it should be corrected even though it is the same "old" 1.2.3 version? Perfect. Thanks!

Is there any way to contribute to the project?



On Sep 19, 2017 01:11, nicolas-f <notifications@github.com> wrote:

Hi, the scattering issue patch has been merged a while ago so it is not necessary to use old spps version.

**Comment by pbasilio** [comment]
I've been trying to replicate some results, but they are pretty far away from each other, the scene is exactly the same, the coefficients too (imported the same txt file), but the results are different.


Average = Measurements on site

SPPS1 = I-Simpa before reinstalling (exe provided by user on github with the scattering corrected)

SPPS lamina 4 again = New install of I-SIMPA

SPPS lamina 4 again 2 = New re-install of I-SIMPA

[cid:4825fca4-bd24-4c72-a474-8824f98126a1]
Thanks!


________________________________
De: nicolas-f <notifications@github.com>
Enviado: martes, 19 de septiembre de 2017 02:11 a. m.
Para: Ifsttar/I-Simpa
CC: pbasilio; State change
Asunto: Re: [Ifsttar/I-Simpa] Recover project file (#73)


Hi, the scattering issue patch has been merged a while ago so it is not necessary to use old spps version.
